- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/omnibase/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/uav/cmd_vel"
  gz_topic_name: "/model/uav/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/odom"
  gz_topic_name: "/model/omnibase/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/image_raw"
  gz_topic_name: "/camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Wrench for force-based omnidirectional control
- ros_topic_name: "/world/tracking_world/wrench"
  gz_topic_name: "/world/tracking_world/wrench"
  ros_type_name: "geometry_msgs/msg/Wrench"
  gz_type_name: "gz.msgs.Wrench"
  direction: ROS_TO_GZ
